GET https://news.ycombinator.com/ HTTP/1.1

###

GET / HTTP/1.1
Host: example.com

###

POST / HTTP/1.1
Host: example.com
Content-Type: application/json

{
    "key": "value"
}

###

GET https://pokeapi.co/api/v2/pokemon HTTP/1.1
Content-Type: application/json

###

GET https://pokeapi.co/api/v2/pokemon/13/ HTTP/1.1
Content-Type: application/json

###

POST https://pokeapi.co/api/v2/pokemon?offset=25&limit=12

###

DELETE https://pokeapi.co/api/v2/item

###

GET http://localhost:8080/sighting HTTP/1.1
Accept: application/json

###

GET /sighting/2 HTTP/1.1
Host: localhost:8080
Accept: application/json

###

POST http://localhost:8080/sighting HTTP/1.1
Content-Type: application/json

{
  "bugType": "Mosquito",
  "description": "mosquitos are jerks",
  "date": "2020-07-04",
  "interest": 0.0
}

###

PUT http://localhost:8080/sighting/2 HTTP/1.1
Content-Type: application/json

{
  "sightingId": 2,
  "bugType": "Cicada",
  "description": "the cicadas are singing in the trees",
  "date": "2020-09-24",
  "interest": 9.245
}

###

DELETE http://localhost:8080/sighting/3 HTTP/1.1